# Generated by Django 4.2.30 on 2026-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_bill_due_date_alter_bill_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('active_users', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('expenses_created', models.IntegerField(default=0)),
                ('income_created', models.IntegerField(default=0)),
                ('bills_created', models.IntegerField(default=0)),
                ('goals_created', models.IntegerField(default=0)),
                ('reports_generated', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
            },
        ),
    ]
